- PDP10/ka10_defs.h
- PDP10/ka10_pd.c
- PDP10/ka10_sys.c
- makefile
Here's a pull request made against your latest master.
The clock can be turned on or off.  When off, it reads as zero.  This condition is detected by ITS, which will emit a warning.
> KA10: Add DeCoriolis clock.

- PDP10/ka10_dpy.c
Thanks to Lars for figuring it out!
Prevents PDSET "S" command from hanging system, but nothing shows up in display window
> KA10: Account for MIT I/O Multiplexor in 340 Display CONI response

- PDP10/ka10_defs.h
- PDP10/ka10_imx.c
- PDP10/ka10_sys.c
- makefile
I'm making an IMX device stub as per this spec:  
https://github.com/larsbrinkhoff/its-archives/blob/master/ailab/ITS_Hardware_Memo_4.pdf
The stub is just enough to satisfy applicaions there's a something there.  I.e. the CONI assign bit is on, and the DONE is on.
Data passed back to the application will probably be 0 or 2048, and there probably won't be any interrupt capabilities.
> KA10: IMX device (A/D converter)

- PDP10/ka10_dpy.c
CC @philbudne 
Sometimes the simulator will open a Type 30 window.  For example, this happens reliably when running the standalone [GALAXY](https://github.com/PDP-10/its/issues/932) program.
> KA10: Type 30 window pops up

- PDP10/ka10_cpu.c
- PDP10/ka10_defs.h
- PDP10/ka10_sys.c
- PDP10/ka10_ten11.c
- makefile
The Rubin 10-11 interface is shared memory between a PDP-10 and eight Unibuses.
> KA10: Rubin 10-11 interface.

- .travis.yml
- PDP10/ka10_auxcpu.c
- PDP10/ka10_cpu.c
- PDP10/ka10_defs.h
- PDP10/ka10_sys.c
- dependencies.sh
- makefile
Simulate MIT I/O device 20 and shared memory with a PDP-6.
The device is used to send I/O bus interrupts between the processors.  Shared memory works much like the 10-11 interface.  The KA10 can read and write PDP-6 core, but not vice versa.
Work in progress.
> KA10: Auxiliary PDP-6 processor

- I7000/i7000_mt.c
This device supports two densities.  Both can be manually set with a
"SET MTA0 LOW|HIGH" or under program control.
This change seems to allow sim_tape to be aware of the density
that the simulated system is operating under.
> I7000: Fix MT density management

- SEL32/sel32_cpu.c
- SEL32/sel32_fltpt.c
- SEL32/sel32_iop.c
- SEL32/sel32_mt.c
- SEL32/sel32_scfi.c
- SEL32/sel32_sys.c
- SEL32/taptools/mkfmtape.c
- SEL32/taptools/tapdump.c
SEL32: Handle multiple EOFs on MT.
SEL32: Correct basemode instruction processing and display errors.
SEL32:Fix ex -m to display basemode instructions.
> SEL32: Add three missing basemode instructions.

- SEL32/sel32_chan.c
- SEL32/sel32_clk.c
- SEL32/sel32_cpu.c
- SEL32/sel32_defs.h
- SEL32/sel32_disk.c
- SEL32/sel32_mt.c
- SEL32/sel32_scfi.c
- SEL32/sel32_sys.c
SEL32: Do some code cleanup.
With these changes the restart command now works in MPX.  That allows online restart to a new sysgen'd image.
Also changed the sel32_scfi.c code to force interrupt in response to an INCH command like sel32_disk.c.
Grab it and I will continue with diags and UTX testing.
> SEL32: Correct opcode processing errors caught by Gould diagnostics.

- PDP10/ka10_ai.c
- PDP10/kx10_defs.h
- PDP10/kx10_sys.c
- makefile
One-off device for the AI KA10.  (Not to be confused with the DC10 data line scanner.)  Useful for running binary-only version of ITS version 724 from 1972.
I'm guessing there may be some similarities to the SA10 (see issue #12).
> KA10: Systems Concepts DC10 disk controller

- PDP10/ka10_auxcpu.c
- PDP10/kx10_cpu.c
ITS 724 has the auxiliary CPU at 1,,040000 rather than 3,,000000.
The AUXCPURANGE define in kx10_cpu.c needs to be replaced with a run-time value determined by a CPU modifier.
> KA10: aux CPU range should be configurable

- PDP10/ka10_auxcpu.c
- PDP10/ka10_dpk.c
- PDP10/ka10_mty.c
- PDP10/ka10_ten11.c
- PDP10/ka10_tk10.c
The typical ITS configuration runs at 100% host CPU utilization.  How do I fix this?  How do I know which devices are not idling properly?
> KA10: ITS idling

- SEL32/sel32_clk.c
- SEL32/sel32_cpu.c
- SEL32/tests/diag.ini
- SEL32/util/makecode.c
- SEL32/util/makefile
SEL32: Fix sel32_clk.c coding error in interval timer code.
SEL32: Update to latest makecode.c utility and add makefile.
SEL32: Update diag.ini file to show how to set boot regs and CSW values.
> SEL32: Add CSW (console switches) and BOOTR (boot regs) variables.

- PDP10/kx10_cpu.c
This is trivial and will facilitate the rapid delivery of incoming packets.
I'm still working on a couple of IMP details, so please hold off on doing anything with the KA10 until tomorrow.
Thanks
> KA10: Rapidly notice asynchronously queued events when enabled

- PDP10/ka10_ch10.c
BTW, github.com/simh/simh master branch now does have all of the slirp changes.
> KA10: Silence GCC 8.3 warning about buffer overflow in CH device

- PDP10/ka10_dpk.c
- PDP10/ka10_mty.c
- PDP10/ka10_tk10.c
As per @markpizz's instructions.
- Don't mess with txdone.
- Declare which unit lines are associated with.
- Don't set UNIT_DISABLE.
Not a full solution to everything in #153.
> KA10: Terminal controller fixes.

- PDP10/kx10_cty.c
Put a negative value in 37 to shut down ITS.
Maybe you want the value of CTY_SWITCH to depend on UNIT_ITSPAGE instead?
> KA10: make "set cpy stop" work for ITS.

- SEL32/sel32_chan.c
- SEL32/sel32_com.c
- SEL32/sel32_con.c
- SEL32/sel32_cpu.c
- SEL32/sel32_defs.h
- SEL32/sel32_disk.c
- SEL32/sel32_hsdp.c
- SEL32/sel32_mt.c
- SEL32/sel32_scfi.c
- SEL32/tests/diag.ini
SEL32: Add disk definitions for UTX and MPX.
SEL32: Add disk initialization for UTX and MPX HSDP & DISK controllers.
SEL32: Add read/write track/sector label simulation for UTX & MPX.
SEL32: Create revised initialization test files for SIMH.
> SEL32: Allow channel address reconfiguration.

- PDP10/ka10_imx.c
- PDP10/kx10_dpy.c
- display/display.c
- sim_video.c
This adds interrupts to the IMX device, which is needed for ITS to use it.  Also adds SDL game controllers as inputs, for Dazzle Dart to be usable.
This is just a draft pull request.  It need not go in yet.
> KA10: Fully working IMX device

- PDP10/ka10_dpk.c
Fix #160 and #166.  Just a draft!
> KA10: Update DPK device.

- display/display.c
- sim_video.c
```
Thread 1 "pdp10-ka" received signal SIGSEGV, Segmentation fault.
0x00007ffff7b8f008 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
(gdb) bt
#0  0x00007ffff7b8f008 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#1  0x00007ffff7b14eda in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#2  0x00007ffff7b151ac in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#3  0x00007ffff7add705 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#4  0x00000000004bc8e2 in vid_close.part ()
#5  0x00000000004bd5e9 in vid_close ()
#6  0x0000000000440285 in display_close ()
#7  0x000000000043eb3d in iii_reset ()
#8  0x000000000044778e in reset_all.constprop ()
#9  0x000000000045dc3e in sim_run_boot_prep ()
#10 0x0000000000464dd1 in run_cmd ()
#11 0x0000000000462a64 in …
```
> KA10: iii_reset crash

- SEL32/sel32_chan.c
- SEL32/sel32_clk.c
- SEL32/sel32_com.c
- SEL32/sel32_con.c
- SEL32/sel32_cpu.c
- SEL32/sel32_defs.h
- SEL32/sel32_disk.c
- SEL32/sel32_fltpt.c
- SEL32/sel32_hsdp.c
- SEL32/sel32_lpr.c
- SEL32/sel32_mfp.c
- SEL32/sel32_mt.c
- SEL32/sel32_scsi.c
- SEL32/sel32_sys.c
- SEL32/taptools/filelist.c
- makefile
SEL32: start code cleanup.
SEL32: add mfp and mfp scsi disk intitial support code.
SEL32: add new files sel32_mfp.c and sel32_scsi.c to makefile.
SEL32: modify sel32_mt.c code to define tape as BTP for UTX.
> SEL32: Correct real time clock interrupt processing.

- PDP10/kx10_dpy.c
ITS uses CONO bits 1000, 400, and 200 to the 340 display.  These are not documented [here](http://bitsavers.org/pdf/dec/graphics/H-340_Type_340_Precision_Incremental_CRT_System_Nov64.pdf).
When running SPCWAR and TWDEMO, ITS wants to do CONO DIS,200.  The comment is "EDGE GRONK DIS AND KEEP GOING".  Possibly to an clear edge hit condition.
@rcornwell, @philbudne, @aap, any ideas are welcome.
> KA10: ITS uses uncodumented Type 344 CONO bits

- SEL32/README.md
- SEL32/sel32_chan.c
- SEL32/sel32_clk.c
- SEL32/sel32_con.c
- SEL32/sel32_cpu.c
- SEL32/sel32_disk.c
- SEL32/sel32_iop.c
- SEL32/sel32_mfp.c
- SEL32/sel32_mt.c
- SEL32/sel32_scsi.c
SEL32: Roll back sim_activate call times to March 7 values.
SEL32: Correct interrupt auto-reset logic.
SEL32: Add initial support for MFP.
SEL32: Correct Coverity detected errors.
> SEL32: Revise channel programming support.

- SEL32/sel32_chan.c
- SEL32/sel32_cpu.c
- SEL32/sel32_disk.c
- SEL32/sel32_mt.c
- SEL32/taptools/mkvmtape.c
SEL32: Do not clear inch address on controller reset instruction.
SEL32: Update mkvmtape processing for MPX3.X SDT tapes.
SEL32: Do not reset base mode bit on LPSD(CM) instructions.
SEL32: Test for wait mode to inhibit history filling with wait instructions.
> SEL32: Correct status after mt advance record command.

- SEL32/sel32_chan.c
- SEL32/sel32_con.c
- SEL32/sel32_cpu.c
- SEL32/sel32_disk.c
- SEL32/sel32_ec.c
- SEL32/sel32_mt.c
- SEL32/sel32_scsi.c
- SEL32/taptools/README.md
- SEL32/taptools/makefile
- SEL32/taptools/mkdiagtape.c
- SEL32/taptools/mkvmtape.c
- SEL32/taptools/tapdump.c
SEL32: Create mkdiagtape utility to generate SEL diagnostic tapes.
SEL32: Update DP disk and Ethernet software for diag detected errors.
SEL32: Update mkvmtape utility to correctly build MPX3X save tapes.
SEL32: Modify taptools makefile for new mkdiagtape utility.
SEL32: Update README.md file for taptools.
> SEL32: Add workaround delay in channel processing for UTX logic errors.

- PDP10/ka10_imx.c
> KA10: Use MATCH_CMD to match command string.

- README.md
- SEL32/README.md
- SEL32/sel32_chan.c
- SEL32/sel32_clk.c
- SEL32/sel32_com.c
- SEL32/sel32_con.c
- SEL32/sel32_cpu.c
- SEL32/sel32_disk.c
- SEL32/sel32_ec.c
- SEL32/sel32_fltpt.c
- SEL32/sel32_hsdp.c
- SEL32/sel32_iop.c
- SEL32/sel32_lpr.c
- SEL32/sel32_mfp.c
- SEL32/sel32_mt.c
- SEL32/sel32_scfi.c
- SEL32/sel32_scsi.c
- SEL32/sel32_sys.c
- SEL32/taptools/README.md
- SEL32/taptools/disk2tap.c
- SEL32/taptools/makefile
SEL32: Correct unused SPAD location test for interrupt control instructions.
SEL32: Correct HSDP test for formatted disk.
SEL32: Add reset channel command processing for each defined device.
SEL32: Add disk2tap utility to taptools.
SEL32: Test for UTX ZMAP in last sector of SCSI disk when formatting.
SEL32: General code cleanup in multiple modules.
> SEL32: Correct map loading for MPX run requested tasks.

- SEL32/sel32_chan.c
- SEL32/sel32_clk.c
- SEL32/sel32_com.c
- SEL32/sel32_con.c
- SEL32/sel32_cpu.c
- SEL32/sel32_defs.h
- SEL32/sel32_ec.c
- SEL32/sel32_hsdp.c
- SEL32/sel32_iop.c
- SEL32/sel32_lpr.c
- SEL32/sel32_mt.c
- SEL32/sel32_scfi.c
- SEL32/sel32_scsi.c
- SEL32/sel32_sys.c
- SEL32/taptools/README.md
- SEL32/taptools/deblk.c
- SEL32/taptools/renum.c
SEL32: Finish adding preio entry to rest of devices.
SEL32: Remove attached test from SIO processing code.
SEL32: Add attached test to each device processing code.
SEL32: Correct renum.c tap tool tp handle large files.
SEL32: Fix device address assignment for sel32_com.c device.
SEL32: Fix deblk to handle more file formatting errors.
> SEL32: Continue Code cleanup and formatting.

- SEL32/sel32_chan.c
- SEL32/sel32_com.c
- SEL32/sel32_cpu.c
- SEL32/sel32_defs.h
- SEL32/sel32_disk.c
- SEL32/sel32_ec.c
- SEL32/taptools/README.md
- SEL32/taptools/eomtap.c
- SEL32/taptools/makefile
- SEL32/tests/SetupNet
SEL32: Add eomtap to taptools & change makefile & README.md.
SEL32: Code cleanup for sel32_chan.c.
SEL32: Leave auto-int active during processing.
SEL32: Expand ethernet to 16 channels.
> SEL32: Update sel32_ec.c to run ecdiags for mode 0, 1, & 2.

- PDP10/pdp6_dct.c
After reading a tape record, WAITS checks the count and fetches any remaining characters.  It's expected that the count be zero if an even number of 36-bit words have been read.
Resolves #242
> KA10: Fix Data Control to clear character count on DATAI/O.

- SEL32/README.md
- SEL32/sel32_chan.c
- SEL32/sel32_cpu.c
- SEL32/sel32_disk.c
- SEL32/sel32_ec.c
- SEL32/sel32_fltpt.c
- SEL32/sel32_hsdp.c
- SEL32/sel32_lpr.c
- SEL32/sel32_scfi.c
- SEL32/sel32_scsi.c
- SEL32/tests/diag.ini
- SEL32/util/makecode.c
SEL32: Remove random tabs from sel32 source.
SEL32: Terminate WAITQ entries when CPU goes to wait state.
SEL32: Update sel32_chan.c to correct handling of IOCL queue prcessing.
SEL32: Add sel32_lpr description and help functions.
SEL32: Remove lpr output assignment in diags.ini.
> SEL32: Update sel32_disk to only do sector/track replacement for disk.

- PDP10/ka10_iii.c
- display/iii.c
The III display looks suboptimal.
Actual:
Expected:
> KA10: Fix III invivible wholine

- PDP10/ka10_tv.c
- PDP10/kx10_defs.h
- PDP10/kx10_dpy.c
- PDP10/kx10_sys.c
- makefile
Add SAIL spacewar buttons.   Similar to MIT's spacewar consoles.
Bits are read with CONI TV.  TV is device 404 "TV camera interface".
Button bits are, from SW[SW,REG]:
```
TPBIT:  1                               ;BIT SIGNIFYING TORP LAUNCH
20
400
10000
200000
THRUBT: 2
40
1000
20000
400000
ROTRBT: 4
100
2000
40000
1000000
ROTLBT: 10
200
4000
100000
2000000
```
FYI @bgbaumgart
> KA10: SAIL spacewar buttons

- README.md
- SEL32/README.md
- SEL32/sel32_chan.c
- SEL32/sel32_cpu.c
- SEL32/sel32_defs.h
- SEL32/sel32_disk.c
- SEL32/sel32_lpr.c
- SEL32/sel32_mt.c
- SEL32/sel32_sys.c
- SEL32/taptools/makefile
- SEL32/taptools/mkdiagtape.c
- SEL32/taptools/mkvmtape.c
- SEL32/taptools/tapdump.c
- SEL32/taptools/tape2disk.c
SEL32: Add debug dump memory functions.
SEL32: Correct line count in sel32_lpr.c.
SEL32: Correct BSR/BSF code in sel32_mt.c for MPX3X SDT handling.
SEL32: General cleanup/speedup of sel32_mt.c code.
SEL32: Add master SDT tape creation in taptools/mkvmtape.c.
SEL32: Fix EOF detection code in taptools/tapdump.c.
> SEL32: Fix SPAD address validation code for MPX3X.

- PDP10/ka10_ten11.c
- PDP10/kx10_cpu.c
- PDP10/kx10_defs.h
First, change order of the TEN11 and AUXCPU address range checks.  AUXCPU should be first so it can shadow part of the TEN11 memory.
Second, add a configurable TEN11 BASE parameter to set the base address of the TEN11 range.
> KA10: Updates for the AUXCPU and TEN11 devices.

- SEL32/README.md
- SEL32/sel32_chan.c
- SEL32/sel32_cpu.c
- SEL32/sel32_defs.h
- SEL32/sel32_disk.c
- SEL32/sel32_hsdp.c
- SEL32/sel32_scfi.c
- SEL32/sel32_scsi.c
SEL32: Correct spelling error in README.md file.
SEL32: Fix Coverity warning error.
SEL32: Update to latest simh release.
> SEL32: Remove use of DEV_DISK in unit flags instead.

- SEL32/README.md
- SEL32/sel32_cpu.c
SEL32: Update README.md to remove taptools reference.
> SEL32: Correct Coverity detected warning errors.

- PDP10/kx10_cpu.c
- PDP10/tests/adrbrk.do
I propose to add the "address break" feature that I claim is present on KA10 and KI10 processors.  It's not present on the PDP-6.  The feature could presumably be used by system software, but I have not seen any hints that it is.  The feature would mainly be for the PiDP-10 and similar consoles.
How it works, in broad strokes: The console has three address conditions: instruction fetch, data fetch, and write.  If any of those match during a memory cycle and the address switches matches the contents of the MA, then an address stop or break is considered.  If the address stop switch is on, the processor will stop.  If the address break switch is on, an APR interrupt is raised and the address break bit is set in the CONI status bits.  On the KA10 the bit can be cleared with a CONO.  The KI10 …
> KA/KI: Address break feature

- PDP10/ka10_ch10.c
- PDP10/ks10_ch11.c
The CH10 device would poll using clock_coschedule with an interval of 1000.  I'm not sure how many milliseconds this ends up being, but it was rather slow.  I have implemented a new heuristic which polls every 0.3 ms if there are incoming packets.  If not, the old poll interval is used.
Experimenting with e.g. listing a remote tape with DUMP shows this is at least ten times faster than before.
> KA10: Faster Chaosnet

- PDP10/kx10_defs.h
- PDP10/kx10_sys.c
- PDP10/pdp6_ge.c
- makefile
This is a terminal multiplexor to emulate the GE DATANET-760 controller.
There are two independent IO bus devices: 70 for input, and 750 for output.  I believe this makes it necessary to make two DEVICE structures.  We only need to expose the GE device to the user, and the internal GTYO device is enabled or disabled automatically.  Maybe there's a better way to accomplish this.
See also https://gunkies.org/wiki/MIT_AI_lab_IO_bus_interface_for_GE_Datanet_760
> PDP6: Add GE DATANET-760 device.

- PDP10/ka10_ten11.c
This adds support for eight ports for the TEN11 device, like the MIT AI KA10 had.  We now have two PDP-11 front ends: the TV-11, and the XGP-11.
> KA10: Eight ports for TEN11

- PDP10/kx10_cpu.c
They auxiliary memory may shadow a portion of the 10-11 range, so it must be checked first.
> KA10: Fix write access for auxiliary processor memory.
