rcornwell/sims

PDP10/ka10_defs.h
PDP10/ka10_dpy.c
PDP10/ka10_sys.c
makefile

(includes cursory makefile changes)

KA10: Add display support

---

PDP10/ka10_defs.h
PDP10/ka10_mty.c
PDP10/ka10_sys.c
makefile

32 ports, up to 80 kbits/s.  7-bit characters only, at least for output.

KA10: Morton box, high-speed terminal multiplexor

---

PDP10/ka10_dpk.c
PDP10/ka10_tk10.c
PDP10/kx10_defs.h
PDP10/kx10_sys.c
makefile

Terminal multiplexer using DMA for output.  16 lines. 
[Here's the memo](https://github.com/larsbrinkhoff/its-archives/blob/master/ailab/dk-10.12h7)

KA10: Systems Concepts DK-10, Datapoint kludge

---

makefile

pdp10-ka and pdp6 targets affected

makefile: Use consistent directory names for dependent files

---

PDP10/ka10_ai.c

KA10: Fix DC10 CONI missing bits.

---

PDP10/kx10_imp.c

- ICMP Echo and Echo reply packets mangled the ICMP checksum when no
mangling was needed.
- Other ICMP message types may still be wrong since they potentially contain
IP header information that may or may not need IP addresses manipulated
- Increased the ARP table size from 8 to 64 since the ARP RFC (826) suggests
that ARP info from all received ARP packets be gathered as ARP broadcasts
are received.  A normal LAN can easily blow over an 8 entry ARP table.

KA10: Fix IMP ICMP and add detailed debug options

---

PDP10/ka10_mty.c
PDP10/ka10_ten11.c

Along the lines in https://github.com/rcornwell/sims/issues/153#issuecomment-529102686

KA10: Restructure MTY device.

---

SEL32/sel32_chan.c
SEL32/sel32_clk.c
SEL32/sel32_com.c
SEL32/sel32_con.c
SEL32/sel32_cpu.c
SEL32/sel32_disk.c
SEL32/sel32_iop.c
SEL32/sel32_lpr.c
SEL32/sel32_mt.c
SEL32/sel32_scfi.c
SEL32/sel32_sys.c
SEL32/tests/diag.ini

SEL32: Add changes to instruction processing to pass more SEL32 diagnostics.

SEL32: Change diagnostic output to fixed fields.

---

SEL32/sel32_chan.c
SEL32/sel32_com.c
SEL32/sel32_con.c
SEL32/sel32_cpu.c
SEL32/sel32_defs.h
SEL32/sel32_disk.c
SEL32/sel32_scfi.c

SEL32: Changes to support diagnostic differences for all CPU's/

---

SEL32/sel32_chan.c
SEL32/sel32_clk.c
SEL32/sel32_com.c
SEL32/sel32_con.c
SEL32/sel32_cpu.c
SEL32/sel32_disk.c
SEL32/sel32_fltpt.c
SEL32/sel32_hsdp.c
SEL32/sel32_scfi.c
SEL32/sel32_sys.c
SEL32/taptools/README.md
SEL32/taptools/deblk.c
SEL32/taptools/diagcopy.c
SEL32/taptools/fmgrcopy.c
SEL32/taptools/makefile
SEL32/taptools/sdtfmgrcopy.c
SEL32/tests/diag.ini
SEL32/tests/sel32_test.ini

Fix up compiler warnings and Coverity warnings.  Ready to merge.

SEL32: Correct Windows and coverity detected warnings.  Add diagcopy.c.

---

SEL32/sel32_chan.c
SEL32/sel32_clk.c
SEL32/sel32_com.c
SEL32/sel32_con.c
SEL32/sel32_cpu.c
SEL32/sel32_defs.h
SEL32/sel32_disk.c
SEL32/sel32_fltpt.c
SEL32/sel32_hsdp.c
SEL32/sel32_iop.c
SEL32/sel32_lpr.c
SEL32/sel32_mt.c
SEL32/sel32_scfi.c
SEL32/sel32_sys.c

SEL32: Update disk devices to hold current STAR in UNIT structure.
SEL32: Add new disk geometry macros.
SEL32: Revise disk formatting support for UTX.
SEL32: Revise INCH command support for all devices.

SEL32: Update console device to pass SEL diags.

---

PDP10/kx10_defs.h
PDP10/kx10_dpy.c
PDP10/kx10_sys.c

KA10: SDL game controllers

---

PDP10/kx10_cpu.c
PDP10/kx10_defs.h
PDP10/kx10_sys.c

Here's the hardware memo: http://www.catb.org/jargon/html/magic-story.html

KA10: Magic switch.

---

SEL32/sel32_chan.c
SEL32/sel32_clk.c
SEL32/sel32_cpu.c
SEL32/sel32_defs.h
SEL32/sel32_disk.c
SEL32/sel32_hsdp.c
SEL32/sel32_lpr.c
SEL32/sel32_mt.c
SEL32/sel32_sys.c

SEL32: Coverity errors.
SEL32: Change UDP/DPII support.

SEL32: Correct interrupt processing during blocked mode.

---

makefile

ka10_lights.c was renamed kx10_lights.c, but makefile wasn't updated.

KA10: lights

---

PDP10/kx10_dpy.c

Draft.  Work in progress.  See #190, #89.

KA10: Fixes for 340 display

---

SEL32/README.md
SEL32/sel32_chan.c
SEL32/sel32_clk.c
SEL32/sel32_com.c
SEL32/sel32_con.c
SEL32/sel32_cpu.c
SEL32/sel32_defs.h
SEL32/sel32_disk.c
SEL32/sel32_fltpt.c

SEL32: Add MFP device support.
SEL32: Inhibit clock interrupt during console output.
SEL32: Update floating point support.
SEL32: Change console input/output processing.

SEL32: Revise channel program processing.

---

SEL32/sel32_chan.c
SEL32/sel32_clk.c
SEL32/sel32_con.c
SEL32/sel32_cpu.c
SEL32/sel32_fltpt.c
SEL32/sel32_scfi.c

SEL32: Replace single precision floating point multiple function.

SEL32: Correct compiler warning error and coverity warning errors.

---

SEL32/sel32_chan.c
SEL32/sel32_clk.c
SEL32/sel32_con.c
SEL32/sel32_cpu.c
SEL32/sel32_defs.h
SEL32/sel32_fltpt.c

SEL32: Revise console output wait times.
SEL32: Change cpu and channel processing of interrupts.
SEL32: Correct read/write byte macro.
SEL32: General code cleanup and debug code removal.

SEL32: Update floating point FLTW & FLTD instructions to pass SEL diags.

---

SEL32/sel32_chan.c
SEL32/sel32_clk.c
SEL32/sel32_con.c
SEL32/sel32_cpu.c
SEL32/sel32_defs.h
SEL32/sel32_disk.c
SEL32/sel32_ec.c
SEL32/sel32_hsdp.c
SEL32/sel32_mt.c

SEL32: Update error status information for ethernet and disks.
SEL32: Update channel program processing.
SEL32: Some minor code cleanup.

SEL32: Add support for ethernet and disk processor diagnostics.

---

SEL32/sel32_chan.c
SEL32/sel32_con.c
SEL32/sel32_cpu.c
SEL32/sel32_disk.c
SEL32/sel32_hsdp.c

SEL32: Correct console echo command.
SEL32: Correct skipinstr useage.

SEL32: Add disk diag support code for disk and hsdp routines.

---

PDP10/ka10_stk.c
PDP10/kx10_dpy.c

I plan to update the 340 window so that F11 toggles full screen.

KA10: Full screen 340 window

---

SEL32/sel32_chan.c
SEL32/sel32_clk.c
SEL32/sel32_com.c
SEL32/sel32_con.c
SEL32/sel32_cpu.c
SEL32/sel32_defs.h
SEL32/sel32_disk.c
SEL32/sel32_ec.c
SEL32/sel32_hsdp.c
SEL32/sel32_iop.c
SEL32/sel32_lpr.c
SEL32/sel32_mfp.c
SEL32/sel32_mt.c
SEL32/sel32_scfi.c
SEL32/sel32_scsi.c
SEL32/sel32_sys.c

SEL32: Correct booting from devices other than 800 & 1000.
SEL32: Add label support to HSDP & UDP disk controllers.
SEL32: Add ECC support to HSDP & UDP disks for diagnostics.

SEL32: Add iocl processing support per device.

---

SEL32/README.md
SEL32/sel32_chan.c
SEL32/sel32_com.c
SEL32/sel32_con.c
SEL32/sel32_cpu.c
SEL32/sel32_disk.c
SEL32/sel32_ec.c
SEL32/sel32_hsdp.c
SEL32/sel32_mt.c
SEL32/sel32_scfi.c
SEL32/sel32_scsi.c

SEL32: Add track/sector replacement support for HSDP.
SEL32: DO some general code cleanup.

SEL32: Correct right halfword nop processing.

---

SEL32/sel32_cpu.c
SEL32/sel32_disk.c
SEL32/sel32_hsdp.c

SEL32: Update UDP/DPII processing for older images

SEL32: Correct interrupt processing for non-configured interrupts

---

PDP10/ka10_mty.c

Ensure only one of input and output can interrupt at the same time.

KA10: Fix MTY bug.

---

PDP10/kx10_dpy.c

The color scope was an experimental display made by DEC.  They only ever made two.  It was declared a failed experiment, and one was given to the MIT AI lab.
It was used at the lab to shoot a film called "Solar Corona".  It's available from the AI films collection.  There are also some display hacks like a waving dot square and game of life.

KA10: color scope.

---

SEL32/sel32_chan.c
SEL32/sel32_con.c
SEL32/sel32_cpu.c
SEL32/sel32_disk.c
SEL32/sel32_ec.c
SEL32/sel32_hsdp.c
SEL32/sel32_iop.c
SEL32/sel32_mfp.c

SEL32: Change Ethernet simh timing.
SEL32: Do more code cleanup.
SEL32: Add preio entries for IOP & MFP devices.

SEL32: Redo SIO, TIO, HIO support code.

---

SEL32/sel32_chan.c
SEL32/sel32_com.c
SEL32/sel32_con.c
SEL32/sel32_cpu.c
SEL32/sel32_defs.h
SEL32/sel32_disk.c
SEL32/sel32_ec.c
SEL32/sel32_hsdp.c
SEL32/sel32_iop.c
SEL32/sel32_lpr.c
SEL32/sel32_mfp.c
SEL32/sel32_mt.c
SEL32/sel32_scfi.c
SEL32/sel32_scsi.c
SEL32/taptools/tap2disk.c

SEL32: Correct DIB functions to return t_stat instead if UINT16.
SEL32: DO more code cleanup.

SEL32: Update sel32_com.c for telnet support in UTX and MPX.

---

SEL32/sel32_chan.c
SEL32/sel32_cpu.c
SEL32/sel32_defs.h
SEL32/sel32_disk.c
SEL32/sel32_ec.c
SEL32/sel32_mt.c
SEL32/tests/SetupNet

SEL32: update to current simh version.
SEL32: do some code cleanup on various modules.
SEL32: update HIO processing in sel32_chan.c.
SEL32: speed up mt handling in sel32_mt.c.
SEL32: Update SetupNet for network setup.

SEL32: Update sel32_ec.c to correctly handle EC diag in modes 0-3.

---

SEL32/sel32_chan.c
SEL32/sel32_con.c
SEL32/sel32_cpu.c
SEL32/sel32_disk.c
SEL32/sel32_ec.c
SEL32/sel32_hsdp.c

SEL32: Update SIO, HIO, STPIO, TOI error processing and CC's returned

---

PDP10/kx10_defs.h
PDP10/kx10_sys.c
PDP10/kx10_tym.c
makefile

New TMXR device to use the TENEX Tymnet interface.

KA10: TymBAS interface.

---

PDP10/kx10_ddc.c
PDP10/kx10_tym.c
Visual Studio Projects/PDP10-KI.vcproj

Updates from Mark.

---

PDP10/ka10_dd.c
PDP10/kx10_tym.c

Fix some warnings reported by @cmgauger.  Captain, please verify this addresses your concerns.

KA10, KI10: Fix some warnings.
